version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
      - postgres_default
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=personal-management
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  vite:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: laravel_vite
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    networks:
      - laravel
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

networks:
  laravel:
    driver: bridge
  postgres_default:
    external: true
    name: postgres_default